networks:
  default:
    name: opentdf_platform
services:
  opentdfdb:
    container_name: opentdfdb
    image: postgres:15-alpine
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: opentdf
    volumes:
      - opentdfdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  opentdfdb_data:
